# Generated by Django 3.2.4 on 2021-06-06 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tinyurl', '0002_rename_shorturl_shorturlmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturlmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
