# Generated by Django 3.2.4 on 2021-06-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyurl', '0003_shorturlmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturlmodel',
            name='click_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
